# Site settings
title: Community Life Engagement
email: Jaimie.Timmons@umb.edu
description: Community Life Engagement refers to the ways people with IDD access and participate in their communities outside of employment, and the supports that enable such engagement. This can include volunteer work; postsecondary, adult, or continuing education; accessing community facilities such as the library, gym, or recreation center; and any activities that people with and without disabilities do in their spare time. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
